import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://dzthyzgsclutgsktumdq.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6dGh5emdzY2x1dGdza3R1bWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NDQwNjUsImV4cCI6MjA3ODEyMDA2NX0.9JgcbS_xeyiGXBRanT-fp7fScJFzd9oteIlXfJVT6lo';

export const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

export const getSessionId = () => {
  let id = localStorage.getItem('eburon_session_id');
  if (!id) {
    id = crypto.randomUUID();
    localStorage.setItem('eburon_session_id', id);
  }
  return id;
};

/*
  *** SQL SETUP INSTRUCTIONS FOR SUPABASE ***
  Run these queries in your Supabase SQL Editor to enable full functionality:

  1. Settings Table:
  create table if not exists settings (
    session_id uuid primary key,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    topic text,
    voice_style text,
    language text
  );

  2. Chat History Table:
  create table if not exists chat_history (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    session_id uuid not null,
    role text not null,
    text text,
    sources jsonb,
    timestamp bigint
  );

  3. Transcriptions Table:
  create table if not exists transcriptions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    session_id uuid not null,
    audio_url text,
    transcript text
  );

  4. Storage Bucket:
  insert into storage.buckets (id, name, public) values ('recordings', 'recordings', true);
  
  (Ensure Row Level Security (RLS) policies allow anon insert/select if you are not using Auth)
*/
